openapi: 3.2.0
info:
  title: Fast Health API
  version: 0.1.0
tags:
- name: Health
paths:
  /health:
    get:
      summary: Status Endpoint
      operationId: status_endpoint_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Status Endpoint Health Get
      tags:
      - Health
servers:
- url: https://api.agoradata.com
  description: Base URL reconciled from apis.yml
